site_name: Recker Family Cookbook
summary: |
  A collection of tried and true recipes, curated and cherished by the
  Recker family.
authors:
  - Alex Recker
  - Jane Recker
  - Sarah Oster
theme: readthedocs
docs_dir: recipes
repo_url: https://github.com/arecker/cookbook/
edit_uri: edit/master/recipes/
markdown_extensions:
  - footnotes
