site_name: Recker Family Cookbook
site_author: Alex Recker
site_description: |
  A collection of tried and true recipes, curated and cherished by the
  Recker family.
theme: readthedocs
docs_dir: recipes
repo_url: https://github.com/arecker/cookbook/
edit_uri: edit/master/recipes/
markdown_extensions:
  - footnotes
